### ISSUE TITLE
UnboundLocalError: local variable 'driver' referenced before assignment

### ISSUE THREAD

**Issue by wupengcheng6819** [peterlacour/finpie#10]
I understand this has to do with Google Chrome. Yet I think I was careful enough to install chrome 86.xxx on my Ubuntu and then finpie==0.133. But I still get this error pulling NewsData

`from finpie import NewsData`
`news = NewsData('XOM', 'exxon mobil')`
`df = news.barrons(datestop = '2020-06-01')`

I got:
`Failed to start driver: expected str, bytes or os.PathLike object, not NoneType
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ubuntu/anaconda3/envs/ssa/lib/python3.8/site-packages/finpie/news_data/news.py", line 608, in barrons
    driver = self._load_driver(caps = 'normal')
  File "/home/ubuntu/anaconda3/envs/ssa/lib/python3.8/site-packages/finpie/base.py", line 106, in _load_driver
    return driver
UnboundLocalError: local variable 'driver' referenced before assignment
`

Python version==3.8; 
and the python environment is configured with the finpie requirement.txt:
```
beautifulsoup4>=4.9.1
dask>=2.11.0
numpy>=1.18.2
pandas>=1.0.1
requests>=2.22.0
requests_html>=0.10.0
selenium>=3.141.0
tqdm>=4.32.1
```

**Comment by peterlacour** [comment]
Hey, 

The problem is that I haven't included a Linux driver in the package.. I can include it at some
point later today but I probably won't have the time to properly test it. I am not sure if everything will work as expected but you can see if it works for you

**Comment by wupengcheng6819** [comment]
Your inclusion for Linux driver is still anticipated. Thank you in advance...

**Comment by peterlacour** [comment]
Included it now and the chrome drivers are updated to 89.XXX. 
Let me know if it works and sorry for the delay, I was working last weekend and didn't have a mind for it.
