### ISSUE TITLE
Values from Macrotrends that are supposed to be negative weren't marked as negative

### ISSUE THREAD

**Issue by dazfran** [peterlacour/finpie#12]
Using the Macrotrends income_statement() function, I found that values that were negative on Macrotrends were missing the preceding '-' character in the resulting dataframe.

**Comment by peterlacour** [comment]
That is fixed now. A bit of an strange thing and not sure if they changed the site but was probably just my mistake

Sorry for the delay and let me know if you find any other oddities. I haven't thoroughly tested all the data so am happy if you find these things
