### ISSUE TITLE
UnboundLocalError: local variable 'driver' referenced before assignment

### ISSUE THREAD

**Issue by philsv** [peterlacour/finpie#4]
Hello,

there is a new error when loading the package:

Failed to start driver: Message: session not created: This version of ChromeDriver only supports Chrome version 85

---------------------------------------------------------------------------
UnboundLocalError                         Traceback (most recent call last)
<ipython-input-4-598777386f3c> in <module>
      7 from io import StringIO
      8 import urllib.request, json
----> 9 from finpie import NewsData
     10 from functools import reduce
     11 from datetime import datetime

~\anaconda3\lib\site-packages\finpie\__init__.py in <module>
     32 from finpie.fundamental_data.mwatch import MwatchData
     33 from finpie.fundamental_data.yahoo import YahooData
---> 34 from finpie.fundamental_data.fool import Earnings
     35 from finpie.fundamental_data.fundamentals import Fundamentals
     36 

~\anaconda3\lib\site-packages\finpie\fundamental_data\__init__.py in <module>
     24 #
     25 
---> 26 from .fundamentals import Fundamentals
     27 from .yahoo import YahooData
     28 from .finviz import FinvizData

~\anaconda3\lib\site-packages\finpie\fundamental_data\fundamentals.py in <module>
     28 from .mwatch import MwatchData
     29 from .yahoo import YahooData
---> 30 from .fool import Earnings
     31 
     32 class FundamentalsClassA(FinvizData, MacrotrendsData, YahooData, Earnings):

~\anaconda3\lib\site-packages\finpie\fundamental_data\fool.py in <module>
    165 
    166 e = Earnings('NFLX')
--> 167 e.transcripts()

~\anaconda3\lib\site-packages\finpie\fundamental_data\fool.py in transcripts(self, html)
     47 
     48         url = 'https://www.fool.com/'
---> 49         driver = self._load_driver('none')
     50 
     51         try:

~\anaconda3\lib\site-packages\finpie\base.py in _load_driver(self, caps)
    100                                 print('Try turning off your firewall...')
    101 
--> 102                 return driver
    103 
    104         def _get_session(self, url):

Might have to do with a new chrome version?

**Comment by peterlacour** [comment]
Yeah looks like I need to include an updated driver for the new chrome version. I'm traveling right now but I'll fix that and some other stuff tomorrow

**Comment by philsv** [comment]
Awesome thanks Peter.

**Comment by higopires** [comment]
Tried to run on Sypder IDE an example from [this](https://pypi.org/project/finpie/#A7) example from the site, but got the same above.
Thanks for the work, Peter.

**Comment by higopires** [comment]
@peterlacour , I saw on your commits that you did some fixing on the repo. I just downloaded finpie, but I'm still having the same error.

**Comment by peterlacour** [comment]
I updated the chromedriver versions on Github in finpie/webdrivers so you could just replace the driver in your finpie/webdrivers folder in your package installation and that should work for now. Otherwise you can install a test version which works for me locally using: 

pip install --index-url https://test.pypi.org/simple/ finpie

I haven't updated the version yet because I am getting a weird Timeout Exception when testing it on Github / Travis CI, although the tests are passing locally for me. I wanted to figure out that problem first before uploading it.

Sorry about that..

**Comment by peterlacour** [comment]
This should be fixed now if you update the package normally. Sorry for the delay and please let me know if there are any other issues :)
